# Generated by Django 5.1 on 2024-08-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_color_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('قرمز', 'قرمز'), ('ابی', 'آبی'), ('سبز', 'سبز'), ('مشکی', 'مشکی'), ('صورتی', 'صورتی'), ('سفید', 'سفید')], default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
