# Generated by Django 5.1 on 2024-08-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_color_remove_product_color_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/category/'),
        ),
        migrations.AlterField(
            model_name='booth',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/booth/'),
        ),
    ]
