# Generated by Django 5.1 on 2024-08-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_category_image_alter_booth_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='Discountـpercentage',
        ),
    ]
