# Generated by Django 5.1 on 2024-08-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_rename_sale_price_product_discountـpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
