# Generated by Django 5.1 on 2024-08-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_product_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
