# Generated by Django 5.1 on 2024-08-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_alter_feature_name_remove_product_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(default='', to='Store.feature'),
        ),
    ]
