# Generated by Django 5.1 on 2024-08-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_alter_product_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
