# Generated by Django 5.1 on 2024-08-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_mysit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MysIT',
        ),
    ]
