# Generated by Django 5.1 on 2024-08-11 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0021_alter_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='booth',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Store.booth'),
        ),
    ]
