# Generated by Django 5.1 on 2024-08-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0023_alter_product_booth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='booth',
        ),
    ]
