# Generated by Django 5.1 on 2024-08-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0024_alter_product_booth'),
        ('Store', '0026_alter_product_booth'),
    ]

    operations = [
    ]
