# Generated by Django 5.1 on 2024-08-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0027_merge_20240811_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='booth',
        ),
    ]
