# Generated by Django 5.1 on 2024-08-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0029_product_booth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
