# Generated by Django 5.1 on 2024-08-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0030_remove_order_product_remove_comments_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, default='', max_length=300, null=True)),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('is_active', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=False)),
                ('Discountـpercentage', models.IntegerField(default=0)),
                ('booth', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.booth')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Store.category')),
                ('colors', models.ManyToManyField(to='Store.color')),
                ('features', models.ManyToManyField(default='', to='Store.feature')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Store.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Store.product'),
        ),
    ]
