# Generated by Django 5.1 on 2024-08-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0033_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/static/img/user.ico', upload_to='uploads/profile/'),
        ),
    ]
