# Generated by Django 5.1 on 2024-08-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0034_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, default='Customer', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='uploads/profile/user.ico', upload_to='uploads/profile/'),
        ),
    ]
