# Generated by Django 5.1 on 2024-08-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0035_profile_role_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='booth',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Store.booth'),
        ),
    ]
