# Generated by Django 5.1 on 2024-08-17 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0036_profile_booth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='booth',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.booth'),
        ),
    ]
