# Generated by Django 5.1 on 2024-08-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0041_alter_profile_booth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='booth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.booth'),
        ),
    ]
