# Generated by Django 5.1 on 2024-08-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0043_alter_profile_booth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='booth',
            new_name='Booth',
        ),
    ]
