# Generated by Django 5.1 on 2024-08-17 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0044_rename_booth_profile_booth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Booth',
        ),
        migrations.AddField(
            model_name='profile',
            name='booth',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.booth'),
        ),
    ]
