# Generated by Django 5.1 on 2024-08-17 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0046_rename_owner_booth_owner_remove_booth_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='booth',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Store.booth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='booth',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.booth'),
        ),
    ]
