# Generated by Django 5.1 on 2024-08-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0047_alter_product_booth_alter_profile_booth'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
