# Generated by Django 5.1 on 2024-08-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0049_booth_popularity_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
