# Generated by Django 5.1 on 2024-08-26 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0053_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.AddField(
            model_name='color',
            name='prd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.product'),
        ),
    ]
