# Generated by Django 5.1 on 2024-08-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0055_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
