# Generated by Django 5.1 on 2024-08-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0056_admin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
