# Generated by Django 5.1 on 2024-08-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0064_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
