# Generated by Django 5.1 on 2024-08-29 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0065_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='image',
        ),
        migrations.CreateModel(
            name='BoothImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='uploads/booth/')),
                ('booth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.booth')),
            ],
        ),
    ]
